# Generated by Django 3.2 on 2022-01-24 15:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('emails', models.CharField(blank=True, max_length=500, null=True)),
                ('shortIntro', models.CharField(blank=True, max_length=200, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('profileImage', models.ImageField(blank=True, default='profiles/user-default.png', null=True, upload_to='profiles/')),
                ('socialGithub', models.CharField(blank=True, max_length=200, null=True)),
                ('socialTwitter', models.CharField(blank=True, max_length=200, null=True)),
                ('socialLinkedin', models.CharField(blank=True, max_length=200, null=True)),
                ('socialYoutube', models.CharField(blank=True, max_length=200, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
