# Generated by Django 3.2 on 2022-01-14 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20220112_2213'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='featuredImage',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to=''),
        ),
    ]
