name: Django CI
on:
  push:
    branches: [ developement ]
  pull_request:
    branches: [ developement ]
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: 0
    - name: login
      uses: actions/heroku@master
      env:
        HEROKU_API_TOKEN: ${{ secrets.HEROKU_API_TOKEN }}
        HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}
      with:
        args: container:login
        
      if: github.ref == 'refs/heads/master' && job.status == 'success'
    - name: set remote
      run: git remote set-url origin https://heroku:$HEROKU_API_TOKEN@git.heroku.com/HEROKU_APP_NAME.git
    - name: push and deploy
      run: git push origin HEAD:master -f